name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main

jobs:
  lint:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jpetrucciani/ruff-check@main

  pytest-linux:
    if: github.event.pull_request.draft == false
    strategy:
        matrix:
            python-version: ["3.9", "3.10", "3.11"]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install Dependencies
        run: |
          poetry env use "${{ matrix.python-version }}"
          poetry install --extras all

      - name: Test with pytest
        run: poetry run pytest
