name: website

# Build the documentation whenever there are new commits on main
on:
  push:
    branches:
      - main

# Security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Install Dependencies
        run: |
          poetry env use "3.11"
          poetry install --extras all

      - name: Build documentation
        run: |
          poetry env use "3.11"
          poetry run pdoc --docformat google src/doubt -o docs

      - name: Compress documentation
        run: tar --directory docs/ -hcf artifact.tar .

      - name: Upload documentation
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: ./artifact.tar

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1
